name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - matplotlib
  - xarray
  - pandas
  - intake-esm
  - fsspec
  - gcsfs
  - nc-time-axis
  - pip
  - pip:
      - sphinx-pythia-theme
